### ISSUE TITLE
Backend > refactor > Criar verificações para os campos name, role, password em Member

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#106]
# OVERVIEW

- Para padronizar os responses nos casos de campos faltando, ao criar novos membros, será necessário adicionar verificações para name, role, password e outros campos request;
- Email já é checado e o padrão dele pode ser replicado para os demais campos.

# TASKS

- [x] Verificação de ausência ou string vazia para o campo name;
- [x] Verificação de ausência ou string vazia para o campo role;
- [x] Verificação de ausência ou string vazia para o campo password;

**Comment by ManoMax** [comment]
#107
