### ISSUE TITLE
Backend > Refactor > Atualizar todas as verificações de role == "presidente" no código.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#21]
# OVERVIEW 
- Com a atualização de roles disponíveis para os membros, a antiga função `presidente` agora tornou-se `Presidente`;
- Isso fez com que uma série de verificações no ambiente Backend, não reconhecesse o usuário com essa função como um usuário de acesso maior;

# TASK
- [ ] Atualize as verificações com a string `presidente` para a função `Presidente`.
  - [ ] dashboard-codex-api/src/middlewares/auth.js
  - [ ] dashboard-codex-api/src/modules/Ej/EjService.js

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/22
