### ISSUE TITLE
Backend > Refactor > Adicionar DTO no retorno de dados aos services de EJ e de links.

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-api#28]
# OVERVIEW 
- Como presente nas últimas atualizações dos membros, os services agora devem retornar dados manipulados pelo Backend ao Frontend, para que não sejam enviados todos os dados armazenados no BD;
- Retornando somente os dados necessários, ocorrerá a filtragem de informações de acesso do usuário final e, desse modo, trará mais segurança ao sistema;
- DTO: Data Transfer Object

# TASK
- [x] Adicionar DTO nas respostas dos services de EJ.
- [x] Adicionar DTO nas respostas dos services de Links.
- [x] Adicionar DTO nas respostas dos services de Member.
- [x] Adicionar DTO nas respostas dos services de Projetos.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/30
