### ISSUE TITLE
Backend > Feature > [Atualizações de Projetos] Criar Rotas e Services (CRUD) para Atualizações do Projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#40]
# OVERVIEW 
- Com o model `News` adicionado ao Backend e com esse model sendo referenciado no Objeto de `Project`, agora é possível criar rotas para criar uma nova atualização, edita-la, visualiza-la e remove-la.

# TASK
- [x] Criar rota e service para um membro (`liderança` ou `pertencente a aquele projeto`) criar novas atualizações;
- [x] Criar rota e service para um membro (qualquer cargo) visualizar todas as atualizações daquele projeto (bem como data que foi criada e quem realizou a atualização);
- [x] Criar rota e service para um membro (`liderança` ou `pertencente a aquele projeto`) editar as atualizações que foram realizadas;
- [x] Criar rota e service para um membro (`liderança` ou `pertencente a aquele projeto`) excluir as atualizações que foram realizadas;

# Links:
- 1º Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/38
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37556856
- 2º Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/39
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37557014

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/62
