### ISSUE TITLE
Backend > Feature > membro = usuário (Adicionar acesso ao sistema para os membros).

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#5]
# OVERVIEW 
- Na atual página de registrar membros, os campos para o cadastro são: `Nome, Data de nascimento, Data de entrada, Habilidades, Diretoria, Email, Telefone e Observações`;
- Enquanto na página de registrar usuários, os campos para o cadastro são: `Nome, Email, Senha, Confirmar Senha e Função`.
- Tornar os membros também usuários fará com que:
  1. O sistema fique mais resumido e intuitivo;
  2. Dará mais transparência e participação dos membros da EJ, com o acesso ao sistema;
  3. Facilitará a lógica de gestão do time;
  4. Resumirá o Model de usuário, atualizando somente algumas informações dos usuários.

# TASK
### Backend
- [x] Atualize os atributos dos modelo de Membro;
- [x] Configure os services de cadastro de um novo usuário e atualização do mesmo;
- [x] Atualize as verificações dos métodos que realizam autenticações com o modelo de Membro.

### Frontend
- [x] Adicione os campos `Email, Senha, Confirmar Senha e Função` na página de "Adicionar membro";
- [x] Configure a permissão de "Adicionar membro" somente possível para as funções de Diretores e Presidente.

# Links:
- Issue of Frontend: https://github.com/codexjr-dev/dashboard-codex-web/issues/8
- Link in Frontend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=33826955

**Comment by ManoMax** [comment]
# COMMENTS

- As atuais Habilidades disponíveis nos campos de "Adicionar membro" são: `Backend, Frontend e Comunicação`. Essas opções poderiam ser ampliadas.
- As atuais Diretorias disponíveis nos campos de "Adicionar membro" são: `Projetos, Presidência e Pessoas`. Essas opções precisam ser ampliadas e atualizadas para as atuais diretorias da EJ: `Presidência, Gente & Gestão, Marketing, Negócios, Projetos e Qualidade`.
- As atuais Funções disponíveis nos campos de "Adicionar usuário" são: `Gerente e Diretor`. Essas opções poderiam ser ampliadas e atualizadas para `Assessor(a), Diretor(a), Presidente e Conselheiro(a)`.
- A feature de configurar as três categorias listadas acima de acordo com a estrutura da EJ, pode ser uma estratégia de escalonamento do projeto.
