### ISSUE TITLE
Backend > Docs > Atualizar README

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#59]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, construa um padrão contendo uma `breve descrição`, `manual de instalação`, possíveis  `configurações`, `tecnologias utilizadas`, `colaboradores` e `licença`.
- Esse mesmo padrão será utilizado no Frontend.

# TASK
- [x] Atualizar README.md com uma `breve descrição`;
- [x] Atualizar README.md com um `manual de instalação`;
- [x] Atualizar README.md com as possíveis  `configurações`;
- [x] Atualizar README.md com as `tecnologias utilizadas`;
- [x] Atualizar README.md com os `colaboradores`;
- [x] Atualizar README.md com uma `licença`.

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/60

**Comment by ManoMax** [comment]
# COMMENTS:

- Será necessário criar novos arquivos .md, são eles: [endpoints.md](https://github.com/codexjr-dev/dashboard-codex-api/blob/main/ENDPOINTS.md), [COLLAB.md](https://github.com/codexjr-dev/dashboard-codex-api/blob/main/COLLAB.md) e [LICENSE.md](https://github.com/usuario/projeto/licenca).
