### ISSUE TITLE
Backend > Docs > Criar o arquivo ENDPOINTS.md com rotas para Members, Project, Link, News e EJ.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#61]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, a partir do conteúdo já descrito no README.md, agora precisamos complementar informações sobre o sistema, informando quais as rotas existentes da API e suas descrições, bem como o conteúdo exigido no Body, Params e Header dessas requisições, além das respostas e erros esperados.
- Para isso, devemos criar um arquivo chamado `ENDPOINTS.md` na raiz do projeto, contendo esses conteúdos.

# TASK
- [x] Criar um arquivo chamado `ENDPOINTS.md` na raiz do projeto;
- [x] Mapear todas as rotas da API;
- [x] Descrever a intenção de cada rota;
- [x] Indicar exigências de body, header e params das rotas;
- [x] Informar quais respostas e erros esperados de cada rota;
- [ ] Deixar um campo separado para adicionar o link da Documentação da API gerada via Postman.

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by FLuiz22** [comment]
#72

**Comment by ManoMax** [comment]
# COMMENTS

- Ficou faltando as rotas relacionadas a EJ;
- Alguém poderia finalizar?

@FLuiz22 @matheusvictoor @Anaritamed @maahog

**Comment by ManoMax** [comment]
# COMMENTS

- Melhorias precisarão ser aplicadas e elas estão citadas aqui: https://github.com/codexjr-dev/projexa-api/issues/86
