### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#63]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie um arquivo chamado `COLLAB.md` na raiz do projeto;
- Esse arquivo deve mapear alguns tópicos como: 
  1. `Breve descrição da CodeX`;
  2. `Orientação de como entrar na CodeX`;
  3. `Breve descrição do projeto`;
  4. `Apresentação do Kanban do projeto`;
  5. `Como funciona cada coluna do Kanban`;
  6. `Como funcionam as TAGS do Kanban`;
  7. `Como criar uma Issue e passa-la pra Backlog`;
  8. `Como assinar uma Issue`;
  9. `Como realizar um PR`;
  10. `Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa`;
  11. `Exposição das Dailies, Sprint Planning e Sprint Retrospective`;
  12. `Exposição da Sprint Review e Sprint Length`.
  13. `Exibir a prototipação do sistema`;
  14. `Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn).`

# TASK
- [x] Criar um arquivo chamado `COLLAB.md` na raiz do projeto;
- [x] Criar uma `Breve descrição da CodeX`;
- [x] Criar uma `Orientação de como entrar na CodeX`;
- [x] Criar uma `Breve descrição do projeto`;
- [x] Criar uma `Apresentação do Kanban do projeto`;
- [x] Criar um tópico de `Como funciona cada coluna do Kanban`;
- [x] Criar um tópico de `Como funcionam as TAGS do Kanban`;
- [x] Criar um tópico de `Como criar uma Issue e passa-la pra Backlog`;
- [x] Criar um tópico de `Como assinar uma Issue`;
- [x] Criar um tópico de `Como realizar um PR`;
- [x] Criar uma `Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa`;
- [x] Criar uma `Exposição das Dailies, Sprint Planning e Sprint Retrospective`;
- [x] Criar uma `Exposição da Sprint Review e Sprint Length`.
- [ ] Criar uma `Exibição da prototipação do sistema`;
- [x] Criar um tópico de `Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn).`

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by ManoMax** [comment]
# COMMENTS

- Uma possível divisão de conteúdos pode ser assim:
  - Breve descrição da CodeX: @Anaritamed 
  - Orientação de como entrar na CodeX: @maahog 
  - Breve descrição do projeto: @maahog 
  - Apresentação do Kanban do projeto: @matheusvictoor 
  - Como funciona cada coluna do Kanban: @matheusvictoor 
  - Como funcionam as TAGS do Kanban: @FLuiz22 
  - Como criar uma Issue e passa-la pra Backlog: @FLuiz22 
  - Como assinar uma Issue: @matheusvictoor 
  - Como realizar um PR: @matheusvictoor 
  - Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa: @carlos-lucenag 
  - Exposição das Dailies, Sprint Review e Sprint Plannings: @carlos-lucenag 
  - Exibir a prototipação do sistema: @danieleolivs 
  - Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn): @danieleolivs

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/76

**Comment by ManoMax** [comment]
# COMMENTS

- Converted to:
  - https://github.com/codexjr-dev/projexa-api/issues/79
  - https://github.com/codexjr-dev/projexa-api/issues/81
  - https://github.com/codexjr-dev/projexa-api/issues/80
  - https://github.com/codexjr-dev/projexa-api/issues/85
  - https://github.com/codexjr-dev/projexa-api/issues/84
  - https://github.com/codexjr-dev/projexa-api/issues/82
