### ISSUE TITLE
Backend > Docs > Criar o arquivo LICENSE.md

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#64]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, a partir do conteúdo já descrito no README.md, agora precisamos complementar informações sobre a licença do sistema;
- Para isso, basta procurar no Github, Google ou outra fonte, o conteúdo textual da licença `GNU General Public License v3.0 (GNU GPLv3)` e adicionar no arquivo `LICENSE.md` localizado na raiz do projeto.

# TASK
- [x] Criar um arquivo chamado `LICENSE.md` na raiz do projeto;
- [x] Adicionar o conteúdo da licença `GNU General Public License v3.0 (GNU GPLv3)` nesse arquivo.
## BONUS
- [x] Se quiser estudar os tipos de Licenças e apresentar para a equipe, a Issue sobe mais 2 pontos.

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by FLuiz22** [comment]
#69

**Comment by ManoMax** [comment]
# COMMENT

- [ ] Por favor, atualize o link do LICENSE.md no README.md
