### ISSUE TITLE
Backend > Tests > Criar testes para as rotas de Members.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#66]
# OVERVIEW 
- Na ideia de garantir segurança nos serviços já criados e agilidade no desenvolvimento de novas implementações, desenvolver uma base de teste para cada rota disponível na API pode ser mais do que útil;
- Sendo assim, dividindo a criação desses testes por etapas, crie um conjunto de testes somente para as rotas da `Members`.

# TASK

- [x] 1. Crie um arquivo chamado `Member.test.js` localizado na pasta `test/integration`;
- [x] 2. Para os casos abaixo, crie um arquivo `members.data.json` localizado na pasta `test/datas`, criando alguns JSON's utilizados nos scripts;
- [x] 3. Crie um teste para: A rota POST `/member`, com os campos vazios;
- [ ] 4. Crie um teste para: A rota POST `/member`, com o campo de name vazio;
- [ ] 5. Crie um teste para: A rota POST `/member`, com o campo de email vazio;
- [ ] 6. Crie um teste para: A rota POST `/member`, com o campo de role vazio;
- [ ] 7. Crie um teste para: A rota POST `/member`, com o campo de password vazio;
- [ ] 8. Crie um teste para: A rota POST `/member`, com o campo de birthDate vazio;
- [ ] 9. Crie um teste para: A rota POST `/member`, com o campo de entryDate vazio;
- [ ] 10. Crie um teste para: A rota POST `/member`, com o campo de department vazio;
- [ ] 11. Crie um teste para: A rota POST `/member`, com todos os campos preenchidos;
- [ ] 12. Crie um teste para: A rota POST `/member`, com o campo de email repetido;
- [ ] 13. Crie um teste para: A rota POST `/member`, com o campo de email mal formatado;
- [ ] 14. Crie um teste para: A rota GET `/member`, sem authorization no header;
- [ ] 15. Crie um teste para: A rota GET `/member`, com o token mal formatado no authorization do header;
- [ ] 16. Crie um teste para: A rota GET `/member`, com o token invalido no authorization do header;
- [ ] 17. Crie um teste para: A rota GET `/member`, com o token válido para Assessor no authorization do header;
- [ ] 18. Crie um teste para: A rota GET `/member`, com o token válido para Presidente no authorization do header;
- [ ] 19. Crie um teste para: A rota GET `/member`, com o token válido para Diretor(a) no authorization do header;
- [ ] 20. Crie um teste para: A rota PATCH `/member/:id`, com um :id invalido;
- [ ] 21. Crie um teste para: A rota PATCH `/member/:id`, sem um :id;
- [ ] 22. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, mas sem authorization no header;
- [ ] 23. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, mas com o token mal formatado no authorization do header;
- [ ] 24. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, mas com o token válido para Assessor (não dono do Membro) no authorization do header;
- [ ] 25. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Assessor (dono do Membro) no authorization do header;
- [ ] 26. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Presidente no authorization do header;
- [ ] 27. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Diretor(a) no authorization do header;
- [ ] 28. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido e com permissão no authorization do header, mas com email mal formatado;
- [ ] 29. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido e com permissão no authorization do header, mas com email mal repetido;
- [ ] 30. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Assessor (dono do Membro) no authorization do header, buscando alterar o role;
- [ ] 31. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Assessor (dono do Membro) no authorization do header, buscando alterar a diretoria;
- [ ] 32. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Liderança no authorization do header, buscando alterar o role;
- [ ] 33. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido para Liderança no authorization do header, buscando alterar a diretoria;
- [ ] 34. Crie um teste para: A rota PATCH `/member/:id`, com um :id válido, com o token válido e com permissão no authorization do header, alterando os demais campos;
- [ ] 35. Crie um teste para: A rota DELETE `/member/:id`, com o :id invalido;
- [ ] 36. Crie um teste para: A rota DELETE `/member/:id`, sem um :id;
- [ ] 37. Crie um teste para: A rota DELETE `/member/:id`, com um :id válido, mas sem authorization no header;
- [ ] 38. Crie um teste para: A rota DELETE `/member/:id`, com um :id válido, com o token mal formatado no authorization do header;
- [ ] 39. Crie um teste para: A rota DELETE `/member/:id`, com um :id válido, mas com o token válido para Assessor no authorization do header;
- [ ] 40. Crie um teste para: A rota DELETE `/member/:id`, com um :id válido, com o token válido para Liderança no authorization do header;

**Comment by nicolaskayamori** [comment]
#108
