### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md > Descrição do Kanban do Projeto e instruções de como assinar issue e fazer PR

### ISSUE THREAD

**Issue by matheusvictoor** [codexjr-dev/projexa-api#81]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie um arquivo chamado `COLLAB.md` na raiz do projeto;
- Esse arquivo deve mapear alguns tópicos como: 
  
  1. `Apresentação do Kanban do projeto`;
  2. `Como funciona cada coluna do Kanban`;
  3. `Como assinar uma Issue`;
  4. `Como realizar um PR`;

# TASK

- [x] Criar uma `Apresentação do Kanban do projeto`;
- [x] Criar um tópico de `Como funciona cada coluna do Kanban`;
- [x] Criar um tópico de `Como assinar uma Issue`;
- [x] Criar um tópico de `Como realizar um PR`;

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by matheusvictoor** [comment]
#76

**Comment by ManoMax** [comment]
# COMMENT

- Main Issue: https://github.com/codexjr-dev/projexa-api/issues/63
