### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md > Apresentação das categorias dos times e exposição das Dailies, Sprint Planning, Retrospective, Review e Sprint Length

### ISSUE THREAD

**Issue by carlos-lucenag** [codexjr-dev/projexa-api#84]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie um arquivo chamado `COLLAB.md` na raiz do projeto;

# TASK
- [x] Criar uma `Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa`;
- [x] Criar uma `Exposição das Dailies, Sprint Planning e  Sprint Retrospective`;
- [x] Criar uma `Exposição da Sprint Review e Sprint Length`.

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by ManoMax** [comment]
# COMMENT

- Main Issue: https://github.com/codexjr-dev/projexa-api/issues/63
