### ISSUE TITLE
Backend > Feature > Adicionar um novo campo/atributo "email" nas informações do cliente (presente no model de Project).

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#89]
# OVERVIEW 
- Para agregar nas informações presentes nos projetos, adicionar um novo campo para o e-mail do cliente pode ser algo muito positivo;

# TASK
- [ ] Atualizar o Model de Projeto, com um campo "email" nas informações do cliente;
- [ ] Atualizar Service de Projeto para adicionar o email às informações do cliente (POST);
- [ ] Atualizar Service de Projeto para editar o email às informações do cliente (PATCH);
- [ ] Atualizar Service de Projeto para receber o email do cliente ao realizar o GET projeto.
